services:
  php:
    build:
      context: .
      target: prod
    # Production overrides
    environment:
      - DB_HOST=mariadb
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      # Add production-specific env vars here
      - PHP_OPCACHE_ENABLE=1
      - PHP_MEMORY_LIMIT=256M