services:
  mariadb:
    image: mariadb:10.6.19
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db-dump:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  php:
    container_name: opencart-app
    restart: unless-stopped
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      # Mount your project files
      - ./public_html:/var/www/html
    depends_on:
      - mariadb
      - redis
    environment:
      - DB_HOST=mariadb
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mariadb_data:
  redis_data: